spring.profiles.active=dev
#spring.profiles.active=dev

# Database Connection Settings
#spring.datasource.url=jdbc:mysql://localhost:3306/tms
#spring.datasource.username=root
#spring.datasource.password=Vaishu@080223
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA/Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true